/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	// Safelist classes used in dynamic database content (generated by content-worker)
	safelist: [
		// Layout
		'max-w-4xl', 'max-w-3xl', 'max-w-2xl', 'max-w-xl', 'mx-auto',
		'px-4', 'px-6', 'px-8', 'py-4', 'py-6', 'py-8', 'sm:px-6', 'lg:px-8',
		'mb-4', 'mb-6', 'mb-8', 'mb-12', 'mt-4', 'mt-6', 'mt-8',
		'space-y-2', 'space-y-4', 'space-y-6',
		// Typography
		'font-sans', 'font-bold', 'font-extrabold', 'font-semibold', 'font-medium',
		'text-xs', 'text-sm', 'text-base', 'text-lg', 'text-xl', 'text-2xl', 'text-3xl', 'text-4xl', 'text-5xl',
		'text-gray-600', 'text-gray-700', 'text-gray-800', 'text-gray-900',
		'text-red-600', 'text-green-600', 'text-blue-600', 'text-blue-700', 'text-yellow-600',
		'leading-relaxed', 'leading-tight', 'tracking-tight', 'tracking-wider', 'uppercase',
		// Colors
		'bg-gray-50', 'bg-gray-100', 'bg-yellow-50', 'bg-green-50', 'bg-red-50', 'bg-blue-50',
		'border-gray-200', 'border-yellow-400', 'border-green-400', 'border-red-400',
		'border-l-4', 'border-b-2',
		// Grid
		'grid', 'grid-cols-2', 'md:grid-cols-2', 'gap-4', 'gap-6',
		// Flex
		'flex', 'flex-shrink-0', 'items-center', 'items-start', 'justify-between',
		// Borders & Rounded
		'rounded-xl', 'rounded-lg', 'rounded-full',
		'border', 'border-2',
		// Shadows
		'shadow-sm', 'shadow-md',
		// Lists
		'list-disc', 'list-inside',
		// Responsive
		'md:text-5xl', 'md:grid-cols-2',
		// Width/Height
		'w-full', 'h-full',
	],
	theme: {
		extend: {},
	},
	plugins: [
		require('@tailwindcss/typography'),
	],
}
